### ISSUE TITLE
Fix Prometheus GET exception

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#323]
Because there is no logging in `ApplicationController` at the moment, I can't provide more information.

Request:
```
curl -X GET \
  http://localhost:8080/api/v1/namespaces/mico-system/services/mico-core/proxy/applications/hello/v1.0.0/deploymentInformation \
  -H 'Accept: application/hal+json' \
  -H 'cache-control: no-cache'
```

Response:
```
{
    "timestamp": "2019-01-28T15:03:59.609+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Could not extract response: no suitable HttpMessageConverter found for response type [class io.github.ust.mico.core.REST.PrometheusResponse] and content type [text/html;charset=utf-8]",
    "path": "/applications/hello/v1.0.0/deploymentInformation"
}
```

Exception:
```
2019-01-28 15:03:59.598 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class io.github.ust.mico.core.REST.PrometheusResponse] and content type [text/html;charset=utf-8]] with root cause

org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class io.github.ust.mico.core.REST.PrometheusResponse] and content type [text/html;charset=utf-8]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:121) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:994) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:977) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:709) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:353) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at io.github.ust.mico.core.REST.ApplicationController.requestValueFromPrometheus(ApplicationController.java:249) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.REST.ApplicationController.getMemoryUsageForPod(ApplicationController.java:239) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.REST.ApplicationController.getUiPodInfo(ApplicationController.java:223) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.REST.ApplicationController.getApplicationDeploymentInformation(ApplicationController.java:190) ~[classes!/:1.0-SNAPSHOT]
```

**Comment by wagnerdk** [comment]
There must be at least one MicoServiceInterface associated with our application. I set this on hold until it is possible to create one.

**Comment by davidkopp** [comment]
Issue can't be reproduced anymore.

**Comment by davidkopp** [comment]
Request to Prometheus returns a HTML document instead of a JSON object.

Headers:
```
[Date:"Tue, 05 Feb 2019 15:07:52 GMT", Content-Type:"text/html; charset=utf-8", Transfer-Encoding:"chunked"]
```

Response body:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Prometheus Time Series Collection and Processing Server</title>
    <link rel="shortcut icon" href="/static/img/favicon.ico?v=bfa37c8ee39d11078662dce16c162a61dccf616c">
    <script src="/static/vendor/js/jquery.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/bootstrap-3.3.1/js/bootstrap.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>

    <link type="text/css" rel="stylesheet" href="/static/vendor/bootstrap-3.3.1/css/bootstrap.min.css?v=bfa37c8ee39d11078662dce16c162a61dccf616c">
    <link type="text/css" rel="stylesheet" href="/static/css/prometheus.css?v=bfa37c8ee39d11078662dce16c162a61dccf616c">

    <script>
      var PATH_PREFIX = "";
      var BUILD_VERSION = "bfa37c8ee39d11078662dce16c162a61dccf616c";
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>


    <link type="text/css" rel="stylesheet" href="/static/css/graph.css?v=bfa37c8ee39d11078662dce16c162a61dccf616c">

    <link type="text/css" rel="stylesheet" href="/static/vendor/rickshaw/rickshaw.min.css?v=bfa37c8ee39d11078662dce16c162a61dccf616c">
    <link type="text/css" rel="stylesheet" href="/static/vendor/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.css?v=bfa37c8ee39d11078662dce16c162a61dccf616c">

    <script src="/static/vendor/rickshaw/vendor/d3.v3.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/rickshaw/vendor/d3.layout.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/rickshaw/rickshaw.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/moment/moment.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/bootstrap3-typeahead/bootstrap3-typeahead.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/fuzzy/fuzzy.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>

    <script src="/static/vendor/mustache/mustache.min.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/js/jquery.selection.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>
    <script src="/static/vendor/js/jquery.hotkeys.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>

    <script src="/static/js/graph.js?v=bfa37c8ee39d11078662dce16c162a61dccf616c"></script>

    <script id="graph_template" type="text/x-handlebars-template"></script>

  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
```
