### ISSUE TITLE
Deployment of MicoServiceInterface fails in `mico-core`

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#345]
Creation of Kubernetes Service fails.

Log:
```
2019-02-01 09:12:47.422 DEBUG 1 --- [pool-1-thread-1] i.g.u.m.core.REST.DeploymentController   : Creating Kubernetes deployment for MICO service 'hello' in version 'v1.0.0' 2019-02-01 09:12:47.878 ERROR 1 --- [pool-1-thread-1] i.g.u.m.core.REST.DeploymentController   : java.lang.NullPointerException

java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.NullPointerException: null
        at io.github.ust.mico.core.mapping.MicoKubernetesClient.createContainerPorts(MicoKubernetesClient.java:126) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.mapping.MicoKubernetesClient.createMicoService(MicoKubernetesClient.java:73) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.REST.DeploymentController.createKubernetesResources(DeploymentController.java:122) ~[classes!/:1.0-SNAPSHOT]
        at io.github.ust.mico.core.REST.DeploymentController.lambda$null$1(DeploymentController.java:84) ~[classes!/:1.0-SNAPSHOT]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[na:1.8.0_181]
        ... 6 common frames omitted
```

**Comment by davidkopp** [comment]
Depends on #282.
List of ports is `null`, however it should be an empty list. Lombok `Singular` feature is used.
