### ISSUE TITLE
Fix sporadic KubernetesClientException

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#572]
Sometimes following error occurs:
```
2019-03-16 13:47:09.465 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Deployment]  with name: [null]  in namespace: [mico-david]  failed.] with root cause

java.net.SocketException: Socket closed
```

Other example (build an image):
```
java.util.concurrent.CompletionException: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Build]  with name: [build-spring-boot-realworld-example-app]  in namespace: [mico-david]  failed.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Build]  with name: [build-spring-boot-realworld-example-app]  in namespace: [mico-david]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.1.3.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-4.1.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:249) ~[kubernetes-client-4.1.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:182) ~[kubernetes-client-4.1.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:439) ~[kubernetes-client-4.1.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:437) ~[kubernetes-client-4.1.3.jar:na]
	at io.github.ust.mico.core.service.imagebuilder.ImageBuilder.createBuild(ImageBuilder.java:212) ~[app/:na]
	at io.github.ust.mico.core.service.imagebuilder.ImageBuilder.build(ImageBuilder.java:172) ~[app/:na]
	at io.github.ust.mico.core.resource.DeploymentResource.buildImageAndWait(DeploymentResource.java:183) ~[app/:na]
	at io.github.ust.mico.core.resource.DeploymentResource.lambda$deploy$0(DeploymentResource.java:129) ~[app/:na]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_181]
	... 3 common frames omitted
Caused by: java.net.SocketTimeoutException: timeout
```

Or (deployment):
```
2019-03-19 01:40:27.036 DEBUG 1 --- [nio-8080-exec-8] o.s.w.f.CommonsRequestLoggingFilter      : Request data: uri=/applications/realworld/v0.0.1/deploy]
2019-03-19 01:40:27.045 ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [CustomResourceDefinition]  with name: [null]  in namespace: [null]  failed.] with root cause

java.net.SocketTimeoutException: Read timed out
```

**Comment by davidkopp** [comment]
Duplicate of #361.
