### ISSUE TITLE
Fix 500 error at endpoint /applications/{shortName}/{version}/status

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#665]
Fix `NullPointerException` at endpoint `GET /applications/{shortName}/{version}/status`.

Response:
```
{
    "timestamp": "2019-03-26T16:30:54.835+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Error while extracting response for type [class io.github.ust.mico.core.dto.response.internal.PrometheusResponseDTO] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.github.ust.mico.core.dto.response.internal.PrometheusResponseDTO[\"data\"])",
    "path": "/applications/realworld/v0.0.1/status"
}
```

Log:
```
2019-03-26 16:30:54.131 DEBUG 1 --- [nio-8080-exec-7] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/applications/realworld/v0.0.1/status]
2019-03-26 16:30:54.680 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Found 1 Kubernetes deployment(s) that match the labels '{ust.mico/name=spring-boot-realworld-example-app, ust.mico/version=v1.0.0}'.
2019-03-26 16:30:54.680  INFO 1 --- [nio-8080-exec-7] i.g.u.m.core.service.MicoStatusService   : The MicoService 'spring-boot-realworld-example-app' with version 'v1.0.0' has '1' available replicas.
2019-03-26 16:30:54.749 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Found 1 Kubernetes service(s) that match the labels '{ust.mico/interface=rest, ust.mico/name=spring-boot-realworld-example-app, ust.mico/version=v1.0.0}'.
2019-03-26 16:30:54.749  INFO 1 --- [nio-8080-exec-7] i.g.u.m.core.service.MicoStatusService   : Service interface with name 'rest' of MicoService 'spring-boot-realworld-example-app' in version 'v1.0.0' has external IP: 23.100.15.40
2019-03-26 16:30:54.780 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Check whether MicoApplication 'realworld' 'v2.0.0' is currently deployed.
2019-03-26 16:30:54.780 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Start checking application deployment status for MicoApplication 'realworld' 'v2.0.0'.
2019-03-26 16:30:54.807 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : There are no service deployment information with Kubernetes deployment information for the MicoApplication 'realworld' 'v2.0.0' stored in the database. MicoApplication is considered to be not deployed.
2019-03-26 16:30:54.808 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : MicoApplication 'realworld' in version 'v2.0.0' is not deployed.
2019-03-26 16:30:54.808 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Check whether MicoApplication 'realworld' 'v1.0.0' is currently deployed.
2019-03-26 16:30:54.808 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Start checking application deployment status for MicoApplication 'realworld' 'v1.0.0'.
2019-03-26 16:30:54.812 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : There are no service deployment information with Kubernetes deployment information for the MicoApplication 'realworld' 'v1.0.0' stored in the database. MicoApplication is considered to be not deployed.
2019-03-26 16:30:54.812 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : MicoApplication 'realworld' in version 'v1.0.0' is not deployed.
2019-03-26 16:30:54.812 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Check whether MicoApplication 'realworld' 'v0.0.1' is currently deployed.
2019-03-26 16:30:54.813 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Start checking application deployment status for MicoApplication 'realworld' 'v0.0.1'.
2019-03-26 16:30:54.816 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : There are no service deployment information with Kubernetes deployment information for the MicoApplication 'realworld' 'v0.0.1' stored in the database. MicoApplication is considered to be not deployed.
2019-03-26 16:30:54.816 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : MicoApplication 'realworld' in version 'v0.0.1' is not deployed.
2019-03-26 16:30:54.825 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.c.service.MicoKubernetesClient   : Found 3 Kubernetes pod(s) that match the labels '{ust.mico/name=spring-boot-realworld-example-app, ust.mico/version=v1.0.0}'.
2019-03-26 16:30:54.825 DEBUG 1 --- [nio-8080-exec-7] i.g.u.m.core.service.MicoStatusService   : Using Prometheus URI 'http://prometheus.monitoring:9090/api/v1/query?query=sum(container_memory_working_set_bytes%7Bpod_name=%22spring-boot-realworld-example-app-b04zv6mz-6d45745b9-cxqdn%22,container_name=%22%22%7D)'
2019-03-26 16:30:54.832 DEBUG 1 --- [nio-8080-exec-7] o.s.w.f.CommonsRequestLoggingFilter      : Request data: uri=/applications/realworld/v0.0.1/status]
2019-03-26 16:30:54.834 ERROR 1 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.RestClientException: Error while extracting response for type [class io.github.ust.mico.core.dto.response.internal.PrometheusResponseDTO] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.github.ust.mico.core.dto.response.internal.PrometheusResponseDTO["data"])] with root cause

java.lang.NullPointerException: null
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:50) ~[app/:na]
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:33) ~[app/:na]
```

Test with `curl` to the mentioned endpoint:
```
curl 'http://localhost:9090/api/v1/query?query=sum(container_memory_working_set_bytes%7Bpod_name=%22spring-boot-realworld-example-app-b04zv6mz-6d45745b9-cxqdn%22,container_name=%22%22%7D)'

{"status":"success","data":{"resultType":"vector","result":[]}}
```

Description of mentioned pod:
```
Name:               spring-boot-realworld-example-app-b04zv6mz-6d45745b9-cxqdn
Namespace:          mico-workspace
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-26424023-3/
Start Time:         Sun, 24 Mar 2019 22:06:50 +0100
Labels:             component=backend
                    pod-template-hash=6d45745b9
                    ust.mico/instance=spring-boot-realworld-example-app-b04zv6mz
                    ust.mico/name=spring-boot-realworld-example-app
                    ust.mico/version=v1.0.0
Annotations:        <none>
Status:             Failed
Reason:             Evicted
Message:            The node was low on resource: memory. Container spring-boot-realworld-example-app was using 531812Ki, which exceeds its request of 0. 
IP:                 
Controlled By:      ReplicaSet/spring-boot-realworld-example-app-b04zv6mz-6d45745b9
Containers:
  spring-boot-realworld-example-app:
    Image:      docker.io/ustmico/spring-boot-realworld-example-app:v1.0.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      APPLICATION_NAME:              REAL_WORLD
      KUBERNETES_PORT_443_TCP_ADDR:  ust-mico-c-ust-mico-resourc-5a45bd-580702af.hcp.westeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://ust-mico-c-ust-mico-resourc-5a45bd-580702af.hcp.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://ust-mico-c-ust-mico-resourc-5a45bd-580702af.hcp.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       ust-mico-c-ust-mico-resourc-5a45bd-580702af.hcp.westeurope.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mgwjr (ro)
Volumes:
  default-token-mgwjr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mgwjr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by davidkopp** [comment]
After a discussion with @marvin21 we came to the following procedure:
* Change the `isAvailable` flag of a pod to `phase` that includes the actual phase the pod currently has (see [Pod phase](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) for more information)
* Only retrieve the pod metrics from Prometheus if the pod is currently in phase `Running`. If not omit the memory usage and the CPU load (or set default values?)
