### ISSUE TITLE
Fix NPE while retrieving metrics from Prometheus

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#764]
Logs:
```
2019-07-23 13:30:25.602 DEBUG 1 --- [io-8080-exec-10] ingFilterConfig$MicoRequestLoggingFilter : BEFORE REQUEST [uri=/applications/test/1.0.0/status/]
2019-07-23 13:30:25.699 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.c.service.MicoKubernetesClient   : Found 1 Kubernetes deployment(s) that match the labels '{ust.mico/name=test-message-generator, ust.mico/version=v1.1.0}'.
2019-07-23 13:30:25.702  INFO 1 --- [io-8080-exec-10] i.g.u.m.core.service.MicoStatusService   : The MicoService 'test-message-generator' with version 'v1.1.0' has '1' available replicas.
2019-07-23 13:30:25.719 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.c.service.MicoKubernetesClient   : Start checking application deployment status for MicoApplication 'test' '1.0.0'.
2019-07-23 13:30:25.855 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.c.service.MicoKubernetesClient   : MicoApplication 'test' in version '1.0.0' is deployed.
2019-07-23 13:30:25.860 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.c.service.MicoKubernetesClient   : Found 1 Kubernetes pod(s) that match the labels '{ust.mico/name=test-message-generator, ust.mico/version=v1.1.0}'.
2019-07-23 13:30:25.861 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.core.service.MicoStatusService   : Using Prometheus URI 'http://prometheus.monitoring:9090/api/v1/query?query=sum(container_memory_working_set_bytes%7Bpod_name=%22test-message-generator-iggn4gkm-cf46df647-sqv9f%22,container_name=%22%22%7D)'
2019-07-23 13:30:25.872 ERROR 1 --- [io-8080-exec-10] i.g.u.m.c.u.PrometheusValueDeserializer  : null

java.lang.NullPointerException: null
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:52) [app/:na]
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:33) [app/:na]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084) [jackson-databind-2.9.9.jar:2.9.9]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:239) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:227) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:102) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:994) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:977) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:354) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at io.github.ust.mico.core.service.MicoStatusService.requestValueFromPrometheus(MicoStatusService.java:370) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getMemoryUsageForPod(MicoStatusService.java:353) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getPodInformation(MicoStatusService.java:339) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getServiceStatus(MicoStatusService.java:186) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getApplicationStatus(MicoStatusService.java:91) [app/:na]
	at io.github.ust.mico.core.broker.MicoApplicationBroker.getApplicationStatus(MicoApplicationBroker.java:324) [app/:na]
	at io.github.ust.mico.core.resource.ApplicationResource.getStatusOfApplication(ApplicationResource.java:291) [app/:na]

2019-07-23 13:30:25.873 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.core.service.MicoStatusService   : Using Prometheus URI 'http://prometheus.monitoring:9090/api/v1/query?query=sum(container_cpu_load_average_10s%7Bpod_name=%22test-message-generator-iggn4gkm-cf46df647-sqv9f%22%7D)'
2019-07-23 13:30:25.882 ERROR 1 --- [io-8080-exec-10] i.g.u.m.c.u.PrometheusValueDeserializer  : null

java.lang.NullPointerException: null
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:52) [app/:na]
	at io.github.ust.mico.core.util.PrometheusValueDeserializer.deserialize(PrometheusValueDeserializer.java:33) [app/:na]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) [jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084) [jackson-databind-2.9.9.jar:2.9.9]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:239) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:227) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:102) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:994) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:977) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:354) [spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at io.github.ust.mico.core.service.MicoStatusService.requestValueFromPrometheus(MicoStatusService.java:370) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getCpuLoadForPod(MicoStatusService.java:358) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getPodInformation(MicoStatusService.java:340) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getServiceStatus(MicoStatusService.java:186) [app/:na]
	at io.github.ust.mico.core.service.MicoStatusService.getApplicationStatus(MicoStatusService.java:91) [app/:na]
	at io.github.ust.mico.core.broker.MicoApplicationBroker.getApplicationStatus(MicoApplicationBroker.java:324) [app/:na]
	at io.github.ust.mico.core.resource.ApplicationResource.getStatusOfApplication(ApplicationResource.java:291) [app/:na]

2019-07-23 13:30:25.904 DEBUG 1 --- [io-8080-exec-10] i.g.u.m.c.service.MicoKubernetesClient   : Start checking application deployment status for MicoApplication 'test' '1.0.0'.
2019-07-23 13:30:25.955 DEBUG 1 --- [io-8080-exec-10] ingFilterConfig$MicoRequestLoggingFilter : AFTER REQUEST [uri=/applications/test/1.0.0/status/]
```

**Comment by davidkopp** [comment]
Fixed by recreating permissions:
```bash
kubectl apply -f install/kubernetes/monitoring/prometheus-rbac.yaml
```
